#!/bin/bash
set -euo pipefail

# Build and install script for legion-laptop.ko
#
# The Makefile auto-detects LLVM toolchain (required for CachyOS/Arch
# kernels built with clang). No manual toolchain flags needed.
#
# Usage:
#   sudo ./build-legion-module.sh              # build, install, and load
#   sudo ./build-legion-module.sh --no-load    # build and install only
#   sudo ./build-legion-module.sh --uninstall  # remove module and configs
#   ./build-legion-module.sh --help
#
# Run this after every kernel update.

# === Configuration ===

MODULE_NAME="legion-laptop"
MODULE_UNDERSCORE="legion_laptop"
KVER="$(uname -r)"
INSTALL_DIR="/lib/modules/${KVER}/kernel/drivers/platform/x86"
BLACKLIST_FILE="/etc/modprobe.d/blacklist-lenovo-wmi.conf"
MODPROBE_CONF="/etc/modprobe.d/legion-laptop.conf"
AUTOLOAD_CONF="/etc/modules-load.d/legion-laptop.conf"
UDEV_RULE_SRC="$(cd "$(dirname "$0")/.." && pwd)/deploy/99-legion-ppd-restart.rules"
UDEV_RULE_DST="/etc/udev/rules.d/99-legion-ppd-restart.rules"

# Upstream modules that conflict with legion-laptop
CONFLICTING_MODULES=(
    lenovo_wmi_gamezone
    lenovo_wmi_other
    lenovo_wmi_events
)

# === Functions ===

usage() {
    cat <<'USAGE'
Usage: sudo ./build-legion-module.sh [OPTIONS]

Options:
  --no-load     Build and install only, do not load the module
  --uninstall   Remove module, blacklist, modprobe conf, and autoload conf
  --help        Show this help message

Steps performed (install):
  1. Build legion-laptop.ko (auto-detects LLVM toolchain)
  2. Install to /lib/modules/$(uname -r)/kernel/drivers/platform/x86/
  3. Run depmod -a
  4. Write blacklist for conflicting upstream modules
  5. Write/preserve modprobe options (platform_profile enabled by default)
  6. Write auto-load config
  7. Install udev rule to restart PPD on platform-profile device add
  8. Unload conflicting modules, load legion-laptop, verify

Steps performed (uninstall):
  1. Unload legion-laptop module
  2. Remove installed .ko from /lib/modules/
  3. Run depmod -a
  4. Remove blacklist, modprobe conf, autoload conf, and udev rule
USAGE
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

check_root() {
    if [ "$(id -u)" -ne 0 ]; then
        die "This script must be run as root (sudo)."
    fi
}

do_build() {
    [ -f Makefile ] || die "Makefile not found in $(pwd) - run from kernel_module/"

    echo "=== Legion Laptop Module Builder ==="
    echo "Kernel:    ${KVER}"
    echo "Toolchain: auto-detected by Makefile (LLVM if kernel was built with clang)"
    echo ""

    echo ">> Cleaning previous build..."
    make clean

    echo ""
    echo ">> Building ${MODULE_NAME}.ko..."
    make

    if [ ! -f "${MODULE_NAME}.ko" ]; then
        die "Build failed: ${MODULE_NAME}.ko not found"
    fi

    echo ""
    echo "Build successful: $(du -sh "${MODULE_NAME}.ko" | cut -f1)"
}

do_install() {
    echo ""
    echo ">> Installing to ${INSTALL_DIR}/..."
    mkdir -p "${INSTALL_DIR}"
    cp -f "${MODULE_NAME}.ko" "${INSTALL_DIR}/"
    echo "   Installed ${MODULE_NAME}.ko"

    echo ""
    echo ">> Running depmod..."
    depmod -a
    echo "   depmod complete"
}

do_blacklist() {
    echo ""
    echo ">> Writing blacklist for conflicting modules..."
    cat > "${BLACKLIST_FILE}" <<EOF
# Blacklist upstream lenovo-wmi modules that conflict with legion-laptop.
# Only the three modules that bind to the same WMI GUIDs are blacklisted.
# Generated by build-legion-module.sh on $(date -I)
EOF
    for mod in "${CONFLICTING_MODULES[@]}"; do
        echo "blacklist ${mod}" >> "${BLACKLIST_FILE}"
    done
    echo "   Wrote ${BLACKLIST_FILE}"
}

do_modprobe_conf() {
    echo ""
    echo ">> Configuring modprobe options..."
    if [ -f "${MODPROBE_CONF}" ]; then
        echo "   Preserving existing ${MODPROBE_CONF}:"
        echo "   $(cat "${MODPROBE_CONF}")"
    else
        cat > "${MODPROBE_CONF}" <<EOF
# legion-laptop module options
# Platform profile enables KDE/GNOME power slider → firmware mode control via PPD
options legion-laptop enable_platformprofile=true
EOF
        echo "   Created ${MODPROBE_CONF}"
        echo "   Platform profile enabled (integrates with power-profiles-daemon)"
    fi
}

do_autoload() {
    echo ""
    echo ">> Configuring auto-load on boot..."
    if [ ! -f "${AUTOLOAD_CONF}" ]; then
        cat > "${AUTOLOAD_CONF}" <<EOF
# Auto-load legion-laptop on boot
legion-laptop
EOF
        echo "   Created ${AUTOLOAD_CONF}"
    else
        echo "   ${AUTOLOAD_CONF} already exists, skipping"
    fi
}

do_udev_rule() {
    echo ""
    echo ">> Installing udev rule for PPD restart..."
    if [ -f "${UDEV_RULE_SRC}" ]; then
        cp -f "${UDEV_RULE_SRC}" "${UDEV_RULE_DST}"
        echo "   Installed ${UDEV_RULE_DST}"
        echo "   (Restarts power-profiles-daemon when platform-profile device appears)"
    else
        echo "   WARN: Source rule not found at ${UDEV_RULE_SRC}, skipping"
    fi
}

do_load() {
    echo ""
    echo ">> Unloading conflicting modules..."
    for mod in "${CONFLICTING_MODULES[@]}"; do
        if lsmod | grep -q "^${mod}"; then
            rmmod "${mod}" 2>/dev/null && echo "   Unloaded ${mod}" || echo "   WARN: Could not unload ${mod}"
        fi
    done

    echo ""
    echo ">> Loading ${MODULE_NAME}..."
    rmmod "${MODULE_UNDERSCORE}" 2>/dev/null || true
    modprobe "${MODULE_NAME}"
    echo "   Module loaded"

    echo ""
    echo ">> Verifying..."
    if lsmod | grep -q "^${MODULE_UNDERSCORE}"; then
        echo "   OK: ${MODULE_UNDERSCORE} is loaded"
    else
        echo "   WARN: ${MODULE_UNDERSCORE} does not appear in lsmod"
    fi

    # Show hwmon fans if available
    local hwmon_dir
    hwmon_dir=$(find /sys/class/hwmon/ -maxdepth 2 -name 'name' -exec grep -l 'legion_laptop' {} \; 2>/dev/null | head -1 | xargs dirname 2>/dev/null || true)
    if [ -n "$hwmon_dir" ]; then
        echo ""
        echo "   hwmon: ${hwmon_dir}"
        for f in "${hwmon_dir}"/fan*_input; do
            [ -f "$f" ] && echo "   $(basename "$f"): $(cat "$f") RPM"
        done
        for f in "${hwmon_dir}"/temp*_input; do
            [ -f "$f" ] && echo "   $(basename "$f"): $(($(cat "$f") / 1000))°C"
        done
    fi
}

do_uninstall() {
    echo "=== Uninstalling ${MODULE_NAME} ==="
    echo ""

    echo ">> Unloading module..."
    rmmod "${MODULE_UNDERSCORE}" 2>/dev/null && echo "   Unloaded" || echo "   Not loaded"

    local ko_path="${INSTALL_DIR}/${MODULE_NAME}.ko"
    if [ -f "$ko_path" ]; then
        echo ">> Removing ${ko_path}..."
        rm -f "$ko_path"
        echo "   Removed"
        depmod -a
        echo "   depmod complete"
    else
        echo ">> ${ko_path} not found, skipping"
    fi

    for f in "${BLACKLIST_FILE}" "${MODPROBE_CONF}" "${AUTOLOAD_CONF}" "${UDEV_RULE_DST}"; do
        if [ -f "$f" ]; then
            echo ">> Removing ${f}..."
            rm -f "$f"
            echo "   Removed"
        fi
    done

    echo ""
    echo "=== Uninstall complete ==="
}

# === Main ===

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

FLAG_NO_LOAD=false
FLAG_UNINSTALL=false

for arg in "$@"; do
    case "$arg" in
        --no-load)    FLAG_NO_LOAD=true ;;
        --uninstall)  FLAG_UNINSTALL=true ;;
        --help|-h)    usage; exit 0 ;;
        *)            die "Unknown option: $arg" ;;
    esac
done

if $FLAG_UNINSTALL; then
    check_root
    do_uninstall
    exit 0
fi

# Build step does not require root (but install does)
do_build

check_root

do_install
do_blacklist
do_modprobe_conf
do_autoload
do_udev_rule

if $FLAG_NO_LOAD; then
    echo ""
    echo "=== Done (--no-load: module not loaded) ==="
    echo "Reboot or run: sudo modprobe ${MODULE_NAME}"
else
    do_load
    echo ""
    echo "=== Done ==="
fi

echo ""
echo "Next steps:"
echo "  1. Check dmesg: dmesg | grep -i legion | tail -10"
echo "  2. Reboot to activate blacklists and udev rule"
echo "  3. KDE/GNOME power slider will control firmware modes via PPD"
echo "     (Quiet / Balanced / Performance)"
